"""Knowledge store protocol — read/write learnings and levels."""

from __future__ import annotations

from typing import Protocol

from agentorg.domain.models import Level


class KnowledgeStore(Protocol):
    """Port for persisting persona, team, and org knowledge."""

    # ── Persona knowledge ──

    def persona_learnings(self, persona_id: str) -> str | None: ...
    def persona_level(self, persona_id: str) -> Level: ...
    def set_persona_level(self, persona_id: str, level: Level) -> None: ...
    def append_persona_learnings(self, persona_id: str, content: str) -> None: ...
    def init_persona(self, persona_id: str) -> None: ...

    # ── Team knowledge ──

    def team_learnings(self, team_id: str) -> str | None: ...
    def team_level(self, team_id: str) -> Level: ...
    def set_team_level(self, team_id: str, level: Level) -> None: ...
    def append_team_learnings(self, team_id: str, content: str) -> None: ...
    def init_team(self, team_id: str) -> None: ...

    # ── Org knowledge ──

    def org_learnings(self) -> str | None: ...
    def append_org_learnings(self, content: str) -> None: ...
    def init_org(self) -> None: ...
