"""Repository protocols for personas, teams, skills, and policies."""

from __future__ import annotations

from typing import Protocol

from agentorg.domain.models import (
    ExecutionPolicy,
    GovernancePolicy,
    ItemSource,
    Persona,
    Skill,
    Team,
)


class PersonaRepository(Protocol):
    def get(self, persona_id: str) -> Persona | None: ...
    def list_all(self) -> list[Persona]: ...
    def list_ids(self) -> list[str]: ...
    def source(self, persona_id: str) -> ItemSource: ...
    def save_to_user(self, persona: Persona) -> None: ...
    def save_to_repo(self, persona: Persona) -> None: ...
    def exists(self, persona_id: str) -> bool: ...


class TeamRepository(Protocol):
    def get(self, team_id: str) -> Team | None: ...
    def list_all(self) -> list[Team]: ...
    def list_ids(self) -> list[str]: ...
    def source(self, team_id: str) -> ItemSource: ...
    def save_to_user(self, team: Team) -> None: ...
    def save_to_repo(self, team: Team) -> None: ...
    def exists(self, team_id: str) -> bool: ...


class SkillRepository(Protocol):
    def get(self, skill_id: str) -> Skill | None: ...
    def list_all(self) -> list[Skill]: ...
    def list_ids(self) -> list[str]: ...
    def source(self, skill_id: str) -> ItemSource: ...
    def save_to_user(self, skill: Skill) -> None: ...
    def save_to_repo(self, skill: Skill) -> None: ...
    def exists(self, skill_id: str) -> bool: ...


class PolicyRepository(Protocol):
    def get_governance(self, profile_id: str) -> GovernancePolicy | None: ...
    def get_execution(self, profile_id: str) -> ExecutionPolicy | None: ...
